### ISSUE TITLE
Хагас И

### ISSUE THREAD

**Issue by tugstugi** [bayartsogt-ya/albert-mongolian#1]
Й-г И-г ээр солиод байх шиг байна. Text normalization чинь проблемтай байгаа юм уу даа. Сургахад бас ингэсэн үү?
```
[CLS] машины ихэнх ачааг жолооч нь дааж баигаа.[SEP]
```

**Comment by bayartsogt-ya** [comment]
```
Й-г И-г ээр солиод байх шиг байна.
```
Аанхаа. 

```
Text normalization чинь проблемтай байгаа юм уу даа.
```
Проблем бол биш гэж бодож байна. Би өөрөө ямар нэг manual normalization share хийсэн модел сургахад хийгдээгүй байгаа.
ALBERT-ийн repo-г дагасан sentencepiece-ийн command-аас хамаараад ижил байдлаар encode хийгдчихээд байгаа.

```
Сургахад бас ингэсэн үү?
```
Сургахдаа яг энэ tokenizer-аа ашиглаад явсан байгаа.
